---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mywebsite-os-scc-storeuser
  labels:
    backstage.io/kubernetes-id: mywebsite-os
    app.kubernetes.io/name: mywebsite-os
    rht-gitops.com/janus-argocd: mywebsite-os
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:saturday-test-k8s1:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mywebsite-os-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: mywebsite-os
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:saturday-test-k8s1:storeuseradmin-sa
